### ISSUE TITLE
[meta] Track experiments with the tracking platform W&B

### ISSUE THREAD

**Issue by marco-c** [mozilla/translations#164]
```[tasklist]
### Bugs
- [ ] https://github.com/mozilla/firefox-translations-training/issues/688
- [ ] https://github.com/mozilla/firefox-translations-training/issues/716
- [ ] https://github.com/mozilla/firefox-translations-training/issues/846
- [ ] https://github.com/mozilla/firefox-translations-training/issues/862
- [ ] Check that COMET is published from the recently archived GCP experiments
- [ ] https://github.com/mozilla/firefox-translations-training/issues/874
```

```[tasklist]
### Reuploading
- [ ] https://github.com/mozilla/firefox-translations-training/issues/793
- [ ] https://github.com/mozilla/firefox-translations-training/issues/863
- [ ] https://github.com/mozilla/firefox-translations-training/issues/574
```

```[tasklist]
### Experiment tracking
- [ ] https://github.com/mozilla/firefox-translations-training/issues/845
- [ ] https://github.com/mozilla/firefox-translations-training/issues/333
- [ ] https://github.com/mozilla/firefox-translations-training/issues/313
- [ ] https://github.com/mozilla/firefox-translations-training/issues/529
- [ ] https://github.com/mozilla/firefox-translations-training/issues/734
- [ ] https://github.com/mozilla/firefox-translations-training/issues/792
- [ ] https://github.com/mozilla/firefox-translations-training/issues/809
- [ ] https://github.com/mozilla/firefox-translations-training/issues/522
- [ ] https://github.com/mozilla/firefox-translations-training/issues/729
- [ ] https://github.com/mozilla/firefox-translations-training/issues/731
- [ ] https://github.com/mozilla/firefox-translations-training/issues/408
- [ ] https://github.com/mozilla/firefox-translations-training/issues/697
- [ ] https://github.com/mozilla/firefox-translations-training/issues/573
- [ ] https://github.com/mozilla/firefox-translations-training/issues/554
- [ ] https://github.com/mozilla/firefox-translations-training/issues/519
- [ ] https://github.com/mozilla/firefox-translations-training/issues/521
- [ ] https://github.com/mozilla/firefox-translations-training/issues/615
- [ ] https://github.com/mozilla/firefox-translations-training/issues/639
- [ ] https://github.com/mozilla/firefox-translations-training/issues/534
- [ ] https://github.com/mozilla/firefox-translations-training/issues/689
- [ ] https://github.com/mozilla/firefox-translations-training/issues/575
- [ ] https://github.com/mozilla/firefox-translations-training/issues/578
- [ ] https://github.com/mozilla/firefox-translations-training/issues/474
- [ ] https://github.com/mozilla/firefox-translations-training/issues/332
- [ ] https://github.com/mozilla/firefox-translations-training/issues/334
- [ ] https://github.com/mozilla/firefox-translations-training/issues/452
- [ ] https://github.com/mozilla/firefox-translations-training/issues/449
- [ ] https://github.com/mozilla/firefox-translations-training/issues/448
- [ ] https://github.com/mozilla/firefox-translations-training/issues/366
- [ ] https://github.com/mozilla/firefox-translations-training/issues/509
- [ ] https://github.com/mozilla/firefox-translations-training/issues/312
- [ ] https://github.com/mozilla/firefox-translations-training/issues/481
- [ ] https://github.com/mozilla/firefox-translations-training/issues/552
- [ ] https://github.com/mozilla/firefox-translations-training/issues/553
- [ ] https://github.com/mozilla/firefox-translations-training/issues/520
- [ ] https://github.com/mozilla/firefox-translations-training/issues/518
- [ ] https://github.com/mozilla/firefox-translations-training/issues/336
- [ ] https://github.com/mozilla/firefox-translations-training/issues/346
- [ ] https://github.com/mozilla/firefox-translations-training/issues/345
- [ ] https://github.com/mozilla/firefox-translations-training/issues/347
- [ ] https://github.com/mozilla/firefox-translations-training/issues/344
- [ ] https://github.com/mozilla/firefox-translations-training/issues/594
```

Docs:
1. [Initial spec](https://docs.google.com/document/d/1iIOdzK8uxvO7QqdoeeKpSkdlM5nxOUmt_HVYpHusQjg/edit?usp=sharing)
2. [Spec by Bastien](https://docs.google.com/document/d/1EKvfHVqi-1zqZavuJ7SgpA-fkXYxQB-Tl6hxrm3_buw/edit#heading=h.ib3mi6quyl4j)
