### ISSUE TITLE
[meta] Make the pipeline reliable enough to train many languages

### ISSUE THREAD

**Issue by gregtatum** [mozilla/translations#311]
This is the lists of tasks that we need to handle in order to ramp up our ability to train many languages. These are things that break training runs, make things difficult to use the pipeline, or make it difficult for multiple people to train at once. 

### Pipeline Usability
- [ ] https://github.com/mozilla/firefox-translations-training/issues/710
- [ ] https://github.com/mozilla/firefox-translations-training/issues/355
- [ ] https://github.com/mozilla/firefox-translations-training/issues/250
- [ ] https://github.com/mozilla/firefox-translations-training/issues/356
- [ ] https://github.com/mozilla/firefox-translations-training/issues/227
- [ ] https://github.com/mozilla/firefox-translations-training/issues/200
- [x] [Update worker-runner in translations generic worker image](https://mozilla-hub.atlassian.net/browse/RELOPS-782)
- [ ] https://github.com/mozilla/firefox-translations-training/issues/330
- [ ] https://github.com/mozilla/firefox-translations-training/issues/354
- [ ] https://github.com/mozilla/firefox-translations-training/issues/155
- [ ] https://github.com/mozilla/firefox-translations-training/issues/182
- [ ] https://github.com/mozilla/firefox-translations-training/issues/395
- [ ] https://github.com/mozilla/firefox-translations-training/issues/582
- [ ] https://github.com/mozilla/firefox-translations-training/issues/653
- [ ] https://github.com/mozilla/firefox-translations-training/issues/538
- [ ] https://github.com/mozilla/firefox-translations-training/issues/655
- [ ] https://github.com/mozilla/firefox-translations-training/issues/654
- [ ] https://github.com/mozilla/firefox-translations-training/issues/630
- [ ] https://github.com/mozilla/firefox-translations-training/issues/628
- [ ] https://github.com/mozilla/firefox-translations-training/issues/640
- [ ] https://github.com/mozilla/firefox-translations-training/issues/680
- [ ] https://github.com/mozilla/firefox-translations-training/issues/562
- [ ] https://github.com/mozilla/firefox-translations-training/issues/711
- [ ] https://github.com/mozilla/firefox-translations-training/issues/728
- [ ] https://github.com/mozilla/firefox-translations-training/issues/806
- [ ] https://github.com/mozilla/firefox-translations-training/issues/855

### Bugs in Training
- [ ] https://github.com/mozilla/firefox-translations-training/issues/314
- [ ] https://github.com/mozilla/firefox-translations-training/issues/293
- [ ] https://github.com/mozilla/firefox-translations-training/issues/292
- [ ] https://github.com/mozilla/firefox-translations-training/issues/272
- [ ] https://github.com/mozilla/firefox-translations-training/issues/663
- [ ] https://github.com/mozilla/firefox-translations-training/issues/649
- [ ] https://github.com/mozilla/firefox-translations-training/issues/679
- [ ] https://github.com/mozilla/firefox-translations-training/issues/631

**Comment by bhearsum** [comment]
Seeing as we're training many languages at once, should we call this done? https://github.com/mozilla/firefox-translations-training/issues/250 is the only remaining issue open in the list, and it is _mostly_ fixed (aside from some UI jank in Taskcluster).

**Comment by eu9ene** [comment]
I think we're still struggling with a bunch of issues, so I'd add them here and keep this one open until we can confidently train new languages without breakage.

**Comment by bhearsum** [comment]
Between this and #490 there are a fairly hefty number of issues related to Taskcluster with various dependencies between them. I created [a simple diagram with dependencies and current status](https://raw.githubusercontent.com/bhearsum/firefox-translations-training/issues/taskcluster-related-issues.mm.svg) to hopefully help with this, which I will try to keep up to date.
