### ISSUE TITLE
[meta] Retrain older high resource models

### ISSUE THREAD

**Issue by evgenyrp** [mozilla/translations#891]
A meta-issue to track retraining of the older models like Italian, Portuguese, French, German, Spanish etc.

We'll need to retrain them to incorporate the latest robustness fixes. Also open-source datasets have improved since we trained them. 

Those are high-resource languages with massive amounts of available training data, so training them is a bit more expensive than a typical language from our last big training. We'll need to do the optimizations first and also fix as many quality issues as we can before retraining not to do this again in the near future.

### Must have
- [x] https://github.com/mozilla/translations/issues/1040
- [x] https://github.com/mozilla/translations/issues/942
- [x] https://github.com/mozilla/translations/issues/76
- [x] https://github.com/mozilla/translations/issues/651
- [x] https://github.com/mozilla/translations/issues/631
- [x] https://github.com/mozilla/translations/issues/1025
- [x] https://github.com/mozilla/translations/issues/711
- [x] https://github.com/mozilla/translations/issues/774
- [x] https://github.com/mozilla/translations/issues/758
- [x] https://github.com/mozilla/translations/issues/177
- [x] https://github.com/mozilla/translations/issues/870
- [x] https://github.com/mozilla/translations/issues/928
- [x] https://github.com/mozilla/translations/issues/903
- [x] https://github.com/mozilla/firefox-translations-training/issues/215
- [ ] https://github.com/mozilla/translations/issues/248

### Nice to have
- [x] https://github.com/mozilla/translations/issues/728
- [x] https://github.com/mozilla/translations/issues/466
- [x] https://github.com/mozilla/translations/issues/736
- [x] https://github.com/mozilla/translations/issues/905
- [x] https://github.com/mozilla/translations/issues/910
- [x] https://github.com/mozilla/translations/issues/783
- [ ] https://github.com/mozilla/translations/issues/940
- [ ] https://github.com/mozilla/translations/issues/634
- [ ] https://github.com/mozilla/translations/issues/394
- [ ] https://github.com/mozilla/translations/issues/987
- [ ] https://github.com/mozilla/translations/issues/92
- [ ] https://github.com/mozilla/translations/issues/1038
- [ ] https://github.com/mozilla/translations/issues/89
- [ ] https://github.com/mozilla/translations/issues/414
- [ ] https://github.com/mozilla/translations/issues/274
- [ ] https://github.com/mozilla/translations/issues/577
- [x] https://github.com/mozilla/translations/issues/800
- [ ] https://github.com/mozilla/translations/issues/737
- [ ] https://github.com/mozilla/translations/issues/415

### Retrain
- [x] Spanish
- [x] Italian
- [x] Portuguese
- [x] German
- [x] French
- [x] Dutch
- [x] Polish
- [x] Bulgarian
- [x] Finnish
- [x] Czech
- [x] Estonian

### Verify
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1888970
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1888897
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1884577
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1881252
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1864472
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1862486
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1853300
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1882997
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1879019
- [x] https://github.com/mozilla/translations/issues/699
- [x] https://github.com/mozilla/bedrock/issues/13357
- [x] https://github.com/mozilla/firefox-translations-models/issues/210
- [x] https://github.com/mozilla/translations/issues/870

**Comment by marco-c** [comment]
After this is done, we'll have to verify the fix with https://github.com/mozilla/translations/issues/757#issuecomment-2239879220.

**Comment by gregtatum** [comment]
Adding a note from [Bug 1954469](https://bugzilla.mozilla.org/show_bug.cgi?id=1954469) that we should make sure and retrain Polish (en-pl). It also needs to be a base model since it's got high morphological complexity, and is exhibiting signs of word invention. The COMET is add the edge of usability according to its score.

**Comment by evgenyrp** [comment]
The work is complete, the models are trained. I verified that most of the robustness issues are now fixed, so we can close this meta issue now. We will triage what's useful from the rest of "nice to have" separately.
